### PR TITLE
Update to Node.js 16, add ncc for prepare script

### LINKED ISSUE #1: Deprecation warnings
This action should be upgraded to use Node.js 16.

### PR DESCRIPTION
**Pull request by tekktrik**
Fixes #1, tested on my own fork of the CircuitPython TestRepo.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Why does the node_module need to be checked in? Can't it be installed as needed?

**Comment by tekktrik** [comment]
I added the ability to use `npm run prepare` just like [the current template action](https://github.com/actions/javascript-action), so I added it to `node_modules/`.  But it's true that it isn't strictly needed for the action itself to function.

**Comment by tannewt** [comment]
I still don't understand why it is checked in. The template you linked to doesn't have a node_modules folder.

**Comment by tekktrik** [comment]
I saw that there were already other things in the node_modules folder in this repo so I added it, but I can remove that specific package if you want.  I'm new to Node.js so I don't truly understand any of the implications of these sort of things, so happy to remove the ncc dependency if that's best.

**Comment by tannewt** [comment]
Haha! I added the other ones. Whoops.

This is fine. :-)

**Review by tannewt — APPROVED** [review]

**Comment by tekktrik** [comment]
Awesome, thanks!

**Comment by tekktrik** [comment]
I'm going to release this and push this as an update to `v1` since nothing changed functionally, and this way the libraries won't need a patch.  Let me know if you prefer a `v2` tag.

**Pull request merged**
